import { ScoringResponse, DIMENSION_META } from '@/app/founder/idea-validator/types/scoring.types';

export const exportToDoc = (report: ScoringResponse, id: string | null) => {
  const dims = DIMENSION_META.map(d => {
    const dim = report.dimensions?.[d.key as keyof typeof report.dimensions];
    if (!dim) return '';
    return `
      <h3>${d.label} &mdash; Score: ${dim.score}/10</h3>
      <p>${dim.why_this_score || ''}</p>
      ${dim.positive_signals?.length ? `<p><strong>Positive Signals:</strong></p><ul>${dim.positive_signals.map(s => `<li>${s}</li>`).join('')}</ul>` : ''}
      ${dim.negative_signals?.length ? `<p><strong>Risk Concerns:</strong></p><ul>${dim.negative_signals.map(s => `<li>${s}</li>`).join('')}</ul>` : ''}
      ${dim.improvement_actions?.length ? `<p><strong>Required Adjustments:</strong></p><ul>${dim.improvement_actions.map(a => `<li>${a}</li>`).join('')}</ul>` : ''}
    `;
  }).join('');

  const redFlags = report.investor_red_flags?.map(f => `<li><strong>${f.flag}</strong> (${f.severity}): ${f.reason}</li>`).join('') || '';
  const riskMatrix = report.risk_matrix ? Object.entries(report.risk_matrix).map(([k, v]: [string, any]) =>
    `<tr><td>${k}</td><td>${v.severity}</td><td>${v.reason}</td><td>${v.mitigation}</td></tr>`
  ).join('') : '';
  const checklist = report.evidence_checklist?.map(c =>
    `<li>[${c.status === 'completed' ? '✓' : c.status === 'partial' ? '~' : '✗'}] ${c.item}: ${c.gap_description}</li>`
  ).join('') || '';
  const roadmapAll = report.validation_roadmap?.map(s =>
    `<li><strong>${s.task}</strong> &mdash; ${s.timeline} | Effort: ${s.effort}<br/>${s.impact}</li>`
  ).join('') || '';

  const documentHtml = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <meta charset="utf-8">
        <title>Venture Readiness Report</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #0F172A; line-height: 1.6; margin: 48px; }
          h1 { font-size: 26pt; color: #0F172A; font-weight: 800; border-bottom: 3px solid #005AE2; padding-bottom: 8px; margin-bottom: 6px; }
          h2 { font-size: 16pt; color: #0F172A; font-weight: 800; margin-top: 32px; margin-bottom: 10px; border-left: 4px solid #005AE2; padding-left: 10px; }
          h3 { font-size: 13pt; color: #0F172A; font-weight: 700; margin-top: 20px; margin-bottom: 8px; }
          p { margin: 0 0 10px 0; font-size: 11pt; }
          ul { margin: 0 0 12px 16px; } li { margin-bottom: 5px; font-size: 11pt; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 24px; margin-top: 12px; }
          th { background: #F8FAFC; font-weight: bold; border-bottom: 2px solid #CBD5E1; padding: 10px 12px; text-align: left; font-size: 9.5pt; color: #0F172A; }
          td { border-bottom: 1px solid #E2E8F0; padding: 12px; font-size: 9.5pt; color: #334155; }
          .meta { font-size: 9.5pt; color: #64748B; margin-bottom: 12px; background: #F8FAFC; border: 1px solid #E2E8F0; padding: 12px 16px; border-radius: 6px; }
          .score-box { display: inline-block; background: #F0F6FF; border: 1.5px solid #BFDBFE; padding: 8px 16px; border-radius: 8px; font-weight: 800; font-size: 14pt; color: #005AE2; margin-bottom: 12px; }
          .section { margin-bottom: 28px; }
          .verdict { background: #F8FAFC; border-left: 4px solid #005AE2; padding: 14px 18px; margin: 16px 0; border-radius: 0 8px 8px 0; border-top: 1px solid #E2E8F0; border-right: 1px solid #E2E8F0; border-bottom: 1px solid #E2E8F0; }
          .risk-high { color: #B91C1C; font-weight: bold; } .risk-med { color: #D97706; font-weight: bold; } .risk-low { color: #0F766E; font-weight: bold; }
        </style>
      </head>
      <body>
        <h1>Investor-Grade Due Diligence Report</h1>
        <p class="meta">Report ID: ${id || 'N/A'} &nbsp;|&nbsp; Generated by CrestCode Venture Studio &nbsp;|&nbsp; Powered by Gemini AI</p>
        <hr/>

        <div class="section">
          <h2>1. Executive Summary</h2>
          <p class="score-box">Readiness Score: ${report.overall_score?.toFixed(1) || '0.0'} / 10</p>
          <p><strong>${(report.overall_score || 0) >= 7.5 ? 'Strong Venture Prospect — Proceed to Build' : (report.overall_score || 0) >= 4.5 ? 'Promising Idea — Needs Validation' : 'High-Risk Concept — Pivot Recommended'}</strong></p>
          <p>${report.startup_summary || report.investor_memo?.executive_summary || ''}</p>
          <div class="verdict">
            <p><strong>AI Strategic Advisory:</strong></p>
            <p>${report.co_founder_recommendations || ''}</p>
          </div>
          ${report.what_increased_the_score?.length ? `<p><strong>Core Strengths:</strong></p><ul>${report.what_increased_the_score.map(s => `<li>${s}</li>`).join('')}</ul>` : ''}
          ${report.what_reduced_the_score?.length ? `<p><strong>Core Risks:</strong></p><ul>${report.what_reduced_the_score.map(s => `<li>${s}</li>`).join('')}</ul>` : ''}
        </div>

        <div class="section">
          <h2>2. Dimension Scores</h2>
          <p><strong>Highest Dimension:</strong> ${report.highest_scoring_dimension || ''} &nbsp;|&nbsp; <strong>Lowest Dimension:</strong> ${report.lowest_scoring_dimension || ''}</p>
          ${dims}
        </div>

        <div class="section">
          <h2>3. VC Investment Memo</h2>
          <p><strong>Biggest Assumption:</strong> ${report.biggest_assumption || ''}</p>
          <h3>Investment Thesis</h3>
          <p>${report.investor_memo?.investment_thesis || ''}</p>
          <h3>Strengths</h3>
          <p>${report.investor_memo?.strengths || ''}</p>
          <h3>Weaknesses</h3>
          <p>${report.investor_memo?.weaknesses || ''}</p>
          <h3>Major Risks</h3>
          <p>${report.investor_memo?.major_risks || ''}</p>
          <h3>Recommendation</h3>
          <p>${report.investor_memo?.recommendation || ''} &mdash; Confidence: ${report.investor_memo?.confidence_rating || ''}</p>
        </div>

        <div class="section">
          <h2>4. Red Flags &amp; Risk Matrix</h2>
          ${redFlags ? `<h3>Venture Red Flags</h3><ul>${redFlags}</ul>` : ''}
          ${riskMatrix ? `<h3>Risk Mitigation Matrix</h3><table><thead><tr><th>Category</th><th>Severity</th><th>Reason</th><th>Mitigation</th></tr></thead><tbody>${riskMatrix}</tbody></table>` : ''}
        </div>

        <div class="section">
          <h2>5. Verification Checklist &amp; Roadmap</h2>
          ${checklist ? `<h3>Evidence Checklist</h3><ul>${checklist}</ul>` : ''}
          ${roadmapAll ? `<h3>Execution Roadmap</h3><ul>${roadmapAll}</ul>` : ''}
        </div>
      </body>
    </html>
  `;

  const blob = new Blob(['\\ufeff' + documentHtml], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Venture_Readiness_Report_${id || 'report'}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
